use energy_bench::EnergyBench;

/// Some function we want to benchmark.
fn factorial(x: u128) -> Result<u128, ()> {
    let res = (1..x).fold(1, u128::saturating_mul);
    Ok(res)
}

fn main() {
    energy_bench::enable_logging(energy_bench::LogLevel::Info);

    let mut bench = EnergyBench::default("minimal");

    for size in [100_000, 1000_000, 10_000_000] {
        // Running a benchmark expects two values:
        // 1) Metadata we might be relevant, such as input data size.
        //    Otherwise, `()` or anything that can be formatted.
        // 2) The function we want to benchmark. This function takes the data generated by the
        //    previous argument as an input. If no data is generated, the input type is `()`.
        //    This function must return some `Result<_>`, which is used for error recovery.
        //    If your function cannot error out, just return `Ok(x)`.
        bench.benchmark(size, &|| factorial(size));
    }
}
